---
title: "Tipos de filme de FULANO(A)"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(cluster)
library(plotly)
library(ggdendro)
library(broom)
library(ggpubr)

source(here::here("code/lib.R"))
theme_set(theme_report())

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5,
                      echo = TRUE)

paleta = c("#404E4D",
           "#92DCE5",
           "#938BA1",
           "#2D3142",
           "#F4743B")
```

```{r}
import_data("johnny_depp")
```


```{r read}
filmes = read_imported_data()
```

## Descrição

```{r}

p = filmes %>% 
    ggplot(aes(x = ano, y = bilheteria, label=filme)) + 
    geom_point(color = paleta[2], size = 4)

ggplotly(p)

```



```{r}
filmes %>% 
    ggplot(aes(x = bilheteria)) + 
    geom_histogram(binwidth = 15, fill = paleta[4], color = "white") 
```

```{r}
filmes %>% 
    ggplot(aes(x = avaliacao)) + 
    geom_histogram(binwidth = 10, boundary = 0, fill = paleta[4], color = "white") + 
    geom_rug(size = .5) 
```

```{r}
bilheteria_ano = filmes %>% 
    group_by(ano) %>% 
    summarise(bilheteria_mediana=median(bilheteria))

avaliacao_ano = filmes %>% 
    group_by(ano) %>% 
    summarise(avaliacao_mediana=median(avaliacao))

p = bilheteria_ano %>% 
    ggplot(aes(x=ano, y=bilheteria_mediana))+
    geom_line(color=paleta[2])+
    geom_point(color="red")

p2 = avaliacao_ano %>% 
    ggplot(aes(x=ano, y=avaliacao_mediana))+
    geom_line(color=paleta[2])+
    geom_point(color="red")

ggplotly(p)
ggplotly(p2)

```


## Estrutura de grupos?

```{r}
m_transformado = filmes %>% 
    mutate(bilheteria_log = as.vector(scale(log10(bilheteria))), 
           avaliacao_scaled = as.vector(scale(avaliacao)))

summary(m_transformado %>% select(bilheteria_log, avaliacao_scaled))
```

```{r}
plot_clusgap = function(clusgap, title = "Gap Statistic calculation results") {
    require("ggplot2")
    gstab = data.frame(clusgap$Tab, k = 1:nrow(clusgap$Tab))
    p = ggplot(gstab, aes(k, gap)) + geom_line() + geom_point(size = 5)
    p = p + geom_errorbar(aes(ymax = gap + SE.sim, ymin = gap - SE.sim), width = .2)
    p = p + ggtitle(title)
    return(p)
}

```

```{r}
gaps <- m_transformado %>% 
    select(bilheteria_log, avaliacao_scaled) %>% 
    clusGap(FUN = kmeans, nstart = 20, K.max = 8, B = 200)

plot_clusgap(gaps)
```

```{r}
n_clusters = 5

# O agrupamento de fato:
cluster = m_transformado %>% 
    select(bilheteria_log, avaliacao_scaled) %>% 
    kmeans(centers = n_clusters, nstart = 20)

agrupado = cluster %>% 
    augment(m_transformado)

#p = agrupado %>% 
#    ggplot(aes(x = avaliacao_scaled, y = bilheteria_log, color = .cluster))  + 
#    geom_point(size = 3)

agrupado %>% 
    ggplot(aes(x = avaliacao, y = bilheteria, color = .cluster))  + 
    geom_point(size = 3)+
    scale_y_log10()

p2 = ggscatter(agrupado, x="avaliacao", y="bilheteria", color=".cluster")+
    stat_chull(aes(fill = .cluster), alpha=0.3, geom="polygon")+
    xlab("Avaliação")+
    ylab("Bilheteria")

ggplotly(p2)

```





